### ISSUE TITLE
Deprecation warnings caused by node-byline dependency

### ISSUE THREAD

**Issue by mistic** [strongloop/strong-log-transformer#7]
@rmg @sam-github On node 10 I'm having deprecation warnings using `strong-log-transformer` due to it's `node-byline` dependency usage of the node `Buffer` api. I've already opened a PR against `node-byline` (https://github.com/jahewson/node-byline/pull/53) in order to fix those problems, but the library seems to be very unmaintained so far, so I don't think if the PR will ever get merged and released. 

In case that happens it might be a good idea try to replace this `node-byline` with other with the same needed features.

**Comment by rmg** [comment]
@mistic thanks for the heads up. I'll see what I can find.

**Comment by rmg** [comment]
@mistic are you using strong-log-transformer directly? Or is it pulled in by something you use? Just trying to get a feel for how best to make sure #8 doesn't break anything.

**Comment by mistic** [comment]
@rmg I'm using it directly right here: https://github.com/elastic/kibana/blob/7a2627797f05f8b0e397c5d13f8d76194064b43c/packages/kbn-pm/src/utils/child_process.ts#L55

**Comment by rmg** [comment]
Cool, thanks for the link. After I posted I did a little searching and was happy to see several uses outside of the original strong-supervisor usage.

It looks like your usage pattern is the most common one. I'll add some ANSI escape codes to some tests to make sure that colourizing things is treated as first-class usage.

**Comment by mistic** [comment]
@rmg thank you very much for taking care of this!

**Comment by rmg** [comment]
@mistic published as `strong-log-transformer@2.1.0` with only the additional tests and the `byline` replacement to keep things conservative.

**Comment by mistic** [comment]
@rmg thank you very much for the quick fix on this!
